name: openjmu
description: A JMU Flutter application.
homepage: https://github.com/openjmu/OpenJMU
publish_to: none
version: 1.0.1+233

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.0
  badges: ^2.0.0-nullsafety.1
  connectivity: ^3.0.2
  cookie_jar: ^3.0.0-beta2
  dartx: ^0.6.0
  device_info: ^2.0.0
  dio: ^4.0.0-beta7
  dio_cookie_manager: ^2.0.0-beta1
  equatable: ^2.0.0
  event_bus: ^2.0.0
  extended_image: ^3.0.0
  extended_list: ^3.0.0
  extended_tabs: ^2.0.0
  extended_nested_scroll_view: ^3.0.0
  extended_text: ^5.0.2
  extended_text_field: ^6.0.1
  ff_annotation_route_library: ^2.0.1
  flutter_displaymode: ^0.2.0-nullsafety.0
  flutter_icons: ^1.1.0
  flutter_inappwebview: ^5.1.0+4
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_native_image: ^0.0.5+3
  flutter_screenutil: 2.3.1
  flutter_svg: ^0.21.0-nullsafety.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  image: ^3.0.1
  image_editor: ^1.0.0-nullsafety.0
  isolate: ^2.0.2
  like_button: ^2.0.1
  loading_more_list: ^4.0.0
  oktoast: ^3.0.0
  open_file: ^3.1.0
  package_info: ^2.0.0
  permission_handler: ^6.0.1+1
  provider: ^5.0.0
  pull_to_refresh_notification: ^2.0.1
  qr_flutter: ^4.0.0
  r_scan:
    git:
      url: https://github.com/CaiJingLong/r_scan.git
      ref: d2f1849f365a1d716d0ade34cfc401f1d6b3d56d
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  vibration: ^1.7.4-nullsafety.0
  video_player: ^2.0.1
  wechat_assets_picker: ^5.0.1
  wechat_camera_picker: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emoji/
    - assets/icons/
    - assets/icons/add-button/
    - assets/icons/app-center/
    - assets/icons/app-center/apps/
    - assets/icons/bottom-navigation/
    - assets/icons/gender/
    - assets/icons/post-actions/
    - assets/icons/publish/
    - assets/icons/self-page/
    - assets/icons/settings/
    - assets/icons/tutorial/
    - assets/icons/user/
    - assets/placeholders/
    - images/
  fonts:
    - family: "chocolate"
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
