name: openjmu
description: A JMU Flutter application.
homepage: https://github.com/openjmu/OpenJMU

version: 1.0.0+208

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: 1.1.2
  badges: ^1.1.6
  connectivity: ^2.0.2
  cookie_jar: 1.0.1
  device_info: ^1.0.0
  dio:
    git:
      url: https://github.com/AlexVincent525/dio.git
      ref: v2.1.16
      path: package_src
  event_bus: 1.1.1
  extended_image: ^1.3.0
  extended_list: ^2.0.2
  extended_tabs: ^0.2.2
  extended_nested_scroll_view: ^2.0.1
  extended_text: ^4.1.0
  extended_text_field: ^5.0.4
  flutter_displaymode: ^0.1.1
  flutter_icons: ^1.1.0
  flutter_inappwebview: ^4.0.0+4
  flutter_local_notifications: ^3.0.3
  flutter_native_image: ^0.0.5+3
  flutter_screenutil: 2.3.1
  flutter_spinkit: 4.1.2+1
  flutter_svg: ^0.19.1
  hive: 1.4.4+1
  hive_flutter: ^0.3.1
  image: 2.1.19
  image_editor: ^0.7.3
  image_save: 4.0.1
  isolate: ^2.0.2
  like_button: ^1.0.4
  loading_more_list: ^3.1.1
  oktoast: 2.3.2
  open_file: 3.0.3
  package_info: ^0.4.3+2
  permission_handler: 5.0.1+1
  provider: ^4.3.2+2
  pull_to_refresh_notification: ^1.1.2
  qr_flutter: 3.2.0
  quick_actions: ^0.4.0+9
  r_scan:
    git:
      url: https://github.com/CaiJingLong/r_scan.git
      ref: d2f1849f365a1d716d0ade34cfc401f1d6b3d56d
  url_launcher: 5.7.10
  uuid: 2.2.2
  vibration: 1.7.3
  video_player: ^1.0.1
  wechat_assets_picker: ^5.0.0-dev.4
  wechat_camera_picker: ^2.0.0-dev.2

dev_dependencies:
  build_runner: ^1.10.7
  extended_image_library: any
  ff_annotation_route: ^4.2.3
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1

dependency_overrides:
  analyzer: ^0.41.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotion-icons/
    - assets/icons/
    - assets/icons/add-button/
    - assets/icons/app-center/
    - assets/icons/app-center/apps/
    - assets/icons/bottom-navigation/
    - assets/icons/gender/
    - assets/icons/post-actions/
    - assets/icons/publish/
    - assets/icons/self-page/
    - assets/icons/settings/
    - assets/icons/user/
    - assets/placeholders/
    - images/
    - images/placeholder/
  fonts:
    - family: "chocolate"
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
