name: openjmu
description: A JMU Flutter application.
homepage: https://github.com/openjmu/OpenJMU

version: 1.0.0+187

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.1
  connectivity: ^0.4.8+6
  cookie_jar: 1.0.1
  device_info: ^0.4.2+4
  dio:
    git:
      url: https://github.com/AlexVincent525/dio.git
      ref: v2.1.16
      path: package_src
  event_bus: 1.1.1
  extended_image: ^0.9.0
  extended_list: ^2.0.0
  extended_tabs: ^0.2.2
  extended_nested_scroll_view: ^1.0.0
  extended_text: 3.0.1
  extended_text_field: 3.0.1
  flutter_displaymode:
    git:
      url: https://github.com/AlexVincent525/flutter_displaymode.git
      ref: "538c10ff"
  flutter_icons: ^1.1.0
  flutter_inappwebview: ^4.0.0+4
  flutter_local_notifications: 1.4.4+2
  flutter_native_image: ^0.0.5
  flutter_screenutil: 1.1.0
  flutter_spinkit: 4.1.2+1
  flutter_svg: ^0.17.4
  flutter_webview_plugin: ^0.3.10
  hive: 1.4.1+1
  hive_flutter: ^0.3.0+2
  image_editor: ^0.7.0
  image_save: 3.1.1
  isolate: ^2.0.2
  like_button: ^1.0.1
  multi_image_picker: 4.6.9
  oktoast: 2.3.2
  open_file: 3.0.1
  package_info: ">=0.4.1 <2.0.0"
  path_provider: 1.6.11
  permission_handler: 5.0.1+1
  provider: ^4.1.3
  pull_to_refresh_notification: ^0.3.5
  qr_flutter: 3.2.0
  quick_actions: ">=0.4.0+6 <2.0.0"
  r_scan:
    git:
      url: https://github.com/rhymelph/r_scan.git
      ref: "ccdf16e"
  url_launcher: 5.5.0
  uuid: 2.2.0
  vibration: 1.4.0
  wechat_assets_picker: ^4.1.0+1

dev_dependencies:
  build_runner: ^1.10.0
  extended_image_library: any
  ff_annotation_route: ^3.3.0
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2

dependency_overrides:
  dartx: ^0.4.2
  image: 2.1.13
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotion-icons/
    - assets/icons/
    - assets/icons/add-button/
    - assets/icons/app-center/
    - assets/icons/bottom-navigation/
    - assets/icons/gender/
    - assets/icons/post-actions/
    - assets/icons/self-page/
    - assets/icons/settings/
    - images/
    - images/placeholder/
  fonts:
    - family: "chocolate"
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
